### ISSUE TITLE
Refactor in SciSharp's libraries

### ISSUE THREAD

**Issue by Oceania2018** [tcmxx/UnityTensorflowKeras#4]
Just read about the features for this project. Seems like `building graph` and `training` are not completed. As I know, TensorFlowSharp can't make training process happen. It's time to consider about refactor this project by using `TensorFlow.NET`, as these [examples](https://github.com/SciSharp/SciSharp-Stack-Examples) it can do many tasks.

We made a RL PPO [example](https://github.com/SciSharp/unity-ml-agents.net) for your reference.

Thanks for paying attention to [SciSharp STACK](http://scisharpstack.org/).

**Comment by tcmxx** [comment]
Tensorflow.Net is super cool, and it basically run in Unity directly.....That is why I am not gonna work on this project anymore....  TensorflowSharp can train stuff. It just does not work directly...

**Comment by Oceania2018** [comment]
OK, sounds great if you can run tf.net in Unity studio directly.
